const REGISTER = {
  REGISTER_INITLIZATION: "REGISTER_INITLIZATION",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERORR: "REGISTER_ERORR"
};

const LOGIN = {
  LOGIN_INITLIZATION: "LOGIN_INITLIZATION",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERORR: "LOGIN_ERORR"
};

const FORGOT_PASSWORD = {
  FORGOT_PASSWORD_INITLIZATION: "FORGOT_PASSWORD_INITLIZATION",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERORR: "FORGOT_PASSWORD_ERORR"
};

const GET_POSTS = {
  GET_POSTS_INITIALIZATION: "GET_POSTS_INITIALIZATION",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_ERROR: "GET_POSTS_ERROR"
};

const ADD_POSTS = {
  ADD_POSTS_INITIALIZATION: "ADD_POSTS_INITIALIZATION",
  ADD_POSTS_SUCCESS: "ADD_POSTS_SUCCESS",
  ADD_POSTS_ERROR: "ADD_POSTS_ERROR"
};

const UPDATE_POSTS = {
  UPDATE_POSTS_INITIALIZATION: "UPDATE_POSTS_INITIALIZATION",
  UPDATE_POSTS_SUCCESS: "UPDATE_POSTS_SUCCESS",
  UPDATE_POSTS_ERROR: "UPDATE_POSTS_ERROR"
};

const GET_PATIENT = {
  GET_PATIENT_INITIALIZATION: "GET_PATIENT_INITIALIZATION",
  GET_PATIENT_SUCCESS: "GET_PATIENT_SUCCESS",
  GET_PATIENT_ERROR: "GET_PATIENT_ERROR"
};

const UPDATE_PATIENT = {
  UPDATE_PATIENT_INITIALIZATION: "UPDATE_PATIENT_INITIALIZATION",
  UPDATE_PATIENT_SUCCESS: "UPDATE_PATIENT_SUCCESS",
  UPDATE_PATIENT_ERROR: "UPDATE_PATIENT_ERROR"
};
const DELETE_POSTS = {
  DELETE_POSTS_INITIALIZATION: "DELETE_POSTS_INITIALIZATION",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_ERROR: "DELETE_POSTS_ERROR"
};


const GET_ALERT_COUNT = {
  GET_ALERT_COUNT_INITIALIZATION: "GET_ALERT_COUNT_INITIALIZATION",
  GET_ALERT_COUNT_SUCCESS: "GET_ALERT_COUNT_SUCCESS",
  GET_ALERT_COUNT_ERROR: "GET_ALERT_COUNT_ERROR"
};


const GET_PHYSICIAN = {
  GET_PHYSICIAN_INITIALIZATION: "GET_PHYSICIAN_INITIALIZATION",
  GET_PHYSICIAN_SUCCESS: "GET_PHYSICIAN_SUCCESS",
  GET_PHYSICIAN_ERROR: "GET_PHYSICIAN_ERROR"
};


const GET_DEVICE = {
  GET_DEVICE_INITIALIZATION: "GET_DEVICE_INITIALIZATION",
  GET_DEVICE_SUCCESS: "GET_DEVICE_SUCCESS",
  GET_DEVICE_ERROR: "GET_DEVICE_ERROR"
};


const ADD_MANAGE_DEVICE = {
  ADD_MANAGE_DEVICE_INITIALIZATION: "ADD_MANAGE_DEVICE_INITIALIZATION",
  ADD_MANAGE_DEVICE_SUCCESS: "ADD_MANAGE_DEVICE_SUCCESS",
  ADD_MANAGE_DEVICE_ERROR: "ADD_MANAGE_DEVICE_ERROR"
};

const DEACTIVATE_PATIENT = {
  DEACTIVATE_PATIENT_INITIALIZATION: "DEACTIVATE_PATIENT_INITIALIZATION",
  DEACTIVATE_PATIENT_SUCCESS: "DEACTIVATE_PATIENT_SUCCESS",
  DEACTIVATE_PATIENT_ERROR: "DEACTIVATE_PATIENT_ERROR"
};

const SEND_MESSAGE = {
  SEND_MESSAGE_INITIALIZATION: "SEND_MESSAGE_INITIALIZATION",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_ERROR: "SEND_MESSAGE_SUCCESS"
};

const DELETE_PATIENT = {
  DELETE_PATIENT_INITIALIZATION: "DELETE_PATIENT_INITIALIZATION",
  DELETE_PATIENT_SUCCESS: "DELETE_PATIENT_SUCCESS",
  DELETE_PATIENT_ERROR: "DELETE_PATIENT_ERROR"
};

const GET_DIAGNOSIS_TYPE = {
  GET_DIAGNOSIS_TYPE_INITIALIZATION: "GET_DIAGNOSIS_TYPE_INITIALIZATION",
  GET_DIAGNOSIS_TYPE_SUCCESS: "GET_DIAGNOSIS_TYPE_SUCCESS",
  GET_DIAGNOSIS_TYPE_ERROR: "GET_DIAGNOSIS_TYPE_ERROR"
};

const ADD_APPOINTMENT = {
  ADD_APPOINTMENT_INITIALIZATION: "ADD_APPOINTMENT_INITIALIZATION",
  ADD_APPOINTMENT_SUCCESS: "ADD_APPOINTMENT_SUCCESS",
  ADD_APPOINTMENT_ERROR: "ADD_APPOINTMENT_ERROR"
};


const GET_VISIT_REASON = {
  GET_VISIT_REASON_INITIALIZATION: "GET_VISIT_REASON_INITIALIZATION",
  GET_VISIT_REASON_SUCCESS: "GET_VISIT_REASON_SUCCESS",
  GET_VISIT_REASON_ERROR: "GET_VISIT_REASON_ERROR"
};

const PATIENT_VIEW = {
  PATIENT_VIEW_INITIALIZATION: "PATIENT_VIEW_INITIALIZATION",
  PATIENT_VIEW_SUCCESS: "PATIENT_VIEW_SUCCESS",
  PATIENT_VIEW_ERROR: "PATIENT_VIEW_ERROR"
};
const PATIENT_DASHBOARD = {
  PATIENT_DASHBOARD_INITIALIZATION: "PATIENT_DASHBOARD_INITIALIZATION",
  PATIENT_DASHBOARD_SUCCESS: "PATIENT_DASHBOARD_SUCCESS",
  PATIENT_DASHBOARD_ERROR: "PATIENT_DASHBOARD_ERROR"
};

const GET_APPOINTMENT = {
  GET_APPOINTMENT_INITIALIZATION: "GET_APPOINTMENT_INITIALIZATION",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_ERROR: "GET_APPOINTMENT_ERROR"
};

export {
  REGISTER, LOGIN, FORGOT_PASSWORD, GET_POSTS,
  UPDATE_POSTS, DELETE_POSTS, ADD_POSTS, GET_PATIENT
  , GET_ALERT_COUNT, GET_PHYSICIAN, UPDATE_PATIENT,
  GET_DEVICE, ADD_MANAGE_DEVICE, DEACTIVATE_PATIENT, SEND_MESSAGE, DELETE_PATIENT,
  GET_DIAGNOSIS_TYPE, ADD_APPOINTMENT, GET_VISIT_REASON, PATIENT_VIEW, PATIENT_DASHBOARD,GET_APPOINTMENT
}


// export { REGISTER, LOGIN, FORGOT_PASSWORD, GET_POSTS, UPDATE_POSTS, DELETE_POSTS, ADD_POSTS,GET_PATIENT, GET_ALERT_COUNT,GET_PHYSICIAN,UPDATE_PATIENT,GET_DEVICE,ADD_MANAGE_DEVICE,PATIENT_DASHBOARD ,PATIENT_VIEW,DEACTIVATE_PATIENT,SEND_MESSAGE,DELETE_PATIENT};
