const REGISTER = {
  REGISTER_INITLIZATION: "REGISTER_INITLIZATION",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERORR: "REGISTER_ERORR"
};

const LOGIN = {
  LOGIN_INITLIZATION: "LOGIN_INITLIZATION",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERORR: "LOGIN_ERORR"
};

const FORGOT_PASSWORD = {
  FORGOT_PASSWORD_INITLIZATION: "FORGOT_PASSWORD_INITLIZATION",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERORR: "FORGOT_PASSWORD_ERORR"
};

const GET_POSTS = {
  GET_POSTS_INITIALIZATION: "GET_POSTS_INITIALIZATION",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_ERROR: "GET_POSTS_ERROR"
};

const ADD_POSTS = {
  ADD_POSTS_INITIALIZATION: "ADD_POSTS_INITIALIZATION",
  ADD_POSTS_SUCCESS: "ADD_POSTS_SUCCESS",
  ADD_POSTS_ERROR: "ADD_POSTS_ERROR"
};

const UPDATE_POSTS = {
  UPDATE_POSTS_INITIALIZATION: "UPDATE_POSTS_INITIALIZATION",
  UPDATE_POSTS_SUCCESS: "UPDATE_POSTS_SUCCESS",
  UPDATE_POSTS_ERROR: "UPDATE_POSTS_ERROR"
};

const GET_CONTACT = {
  GET_CONTACT_INITIALIZATION: "GET_CONTACT_INITIALIZATION",
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS",
  GET_CONTACT_ERROR: "GET_CONTACT_ERROR"
};

const DELETE_POSTS = {
  DELETE_POSTS_INITIALIZATION: "DELETE_POSTS_INITIALIZATION",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_ERROR: "DELETE_POSTS_ERROR"
};


const GET_ALERT_COUNT = {
  GET_ALERT_COUNT_INITIALIZATION: "GET_ALERT_COUNT_INITIALIZATION",
  GET_ALERT_COUNT_SUCCESS: "GET_ALERT_COUNT_SUCCESS",
  GET_ALERT_COUNT_ERROR: "GET_ALERT_COUNT_ERROR"
};

/*
const DELETE_POSTS = {
  DELETE_POSTS_INITIALIZATION: "DELETE_POSTS_INITIALIZATION",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_ERROR: "DELETE_POSTS_ERROR"
};


const DELETE_POSTS = {
  DELETE_POSTS_INITIALIZATION: "DELETE_POSTS_INITIALIZATION",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_ERROR: "DELETE_POSTS_ERROR"
};


const DELETE_POSTS = {
  DELETE_POSTS_INITIALIZATION: "DELETE_POSTS_INITIALIZATION",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_ERROR: "DELETE_POSTS_ERROR"
};


const DELETE_POSTS = {
  DELETE_POSTS_INITIALIZATION: "DELETE_POSTS_INITIALIZATION",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_ERROR: "DELETE_POSTS_ERROR"
};
*/
export { REGISTER, LOGIN, FORGOT_PASSWORD, GET_POSTS, UPDATE_POSTS, DELETE_POSTS, ADD_POSTS,GET_CONTACT, GET_ALERT_COUNT };
